version: 0.0
os: linux
files:
  - source: target/basic-1.war
    destination: /opt/apache-tomcat-10.0.8/webapps
hooks:
  BeforeInstall:    
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
