- hosts: dev
  become: yes
  tasks:
  - name: Install pip
    apt:
      name: python-pip
      state: present
  - name: Install docker
    apt:
      name: docker.io
      state: present    
  - name: Install docker-py
    pip:
      name: docker-py
      state: present
  - name: Restart docker
    service:
      name: docker
      state: restarted
  - name: Download image
    docker_image:      
      repository: jayaneel/testing:0.2
      source: pull
      force_source: yes
  - name: Launch container
    docker_container:
      name: prince
      image: jayaneel/testing:0.2
      published_ports:
        - 0.0.0.0:8080:8080
      state: started
      recreate: yes
