#!/bin/bash
apt update
apt upgrade -y
apt install openjdk-11-jdk -y
cd /tmp
wget https://mirrors.estointernet.in/apache/tomcat/tomcat-10/v10.0.8/bin/apache-tomcat-10.0.8.tar.gz
tar xf /tmp/apache-tomcat-10*.tar.gz -C /opt